services:
  jupyter:
    image: pytorch/pytorch:2.4.0-cuda12.1-cudnn8-runtime
    container_name: datasci-jupyter-gpu
    gpus: 'all'
    environment:
      TZ: Asia/Seoul
      JUPYTER_TOKEN: ${JUPYTER_TOKEN-idas}
      NVIDIA_VISIBLE_DEVICES: 'all'
      NVIDIA_DRIVER_CAPABILITIES: 'compute,utility'
    ports:
      - '${HOST_PORT-8888}:8888'
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data
    working_dir: /workspace
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser
                  --NotebookApp.token=${JUPYTER_TOKEN-idas}
    restart: unless-stopped
